### ISSUE TITLE
Post list order is incorrect

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/noddity-render-static#11]
Should be

``` js
posts.reverse().filter(function(post) {
    return typeof post.metadata.title === 'string' && post.metadata.date
}).map(function(post) {
    return extend(post, post.metadata)
})
```

**Comment by ArtskydJ** [comment]
Related: https://github.com/ArtskydJ/noddity/issues/1

**Comment by TehShrike** [comment]
Oh man, what was that related issue :-x

**Comment by ArtskydJ** [comment]
Whoops! I think it was the same issue, but maybe a bit of discussion?

If I remember correctly, we were thinking of changing `noddity-retrieval`, `noddity-butler`, `noddity-render-static`, and `noddity-render-dom` so that they would not modify the posts array from the index.json file.
